services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fp_api
    restart: unless-stopped
    env_file:
      - .env
    environment:
      SERVER_PORT: 5000
      SPRING_DATASOURCE_URL: ${DB_URL}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      IA_SERVICE_URL: ${IA_SERVICE_URL}
      IA_SERVICE_API_KEY: ${IA_SERVICE_API_KEY}
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQL8Dialect
      SPRING_JPA_HIBERNATE_DDL_AUTO: none

    ports:
      - "5000:5000"
    networks:
      - farmacia-ko2-network

networks:
  farmacia-ko2-network:
    external: true
