# ==========================================
# 1. CONFIGURACION GLOBAL
# ==========================================
spring.application.name=fp-api
server.port=5000

# Tu clave JWT
jwt.secret=${JWT_SECRET}

# ==========================================
# 2. CONFIGURACION JPA / HIBERNATE
# ==========================================
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# IMPORTANTE: 'none' para que no borre las tablas de la nube
spring.jpa.hibernate.ddl-auto=none

# ==========================================
# 3. CONEXION CLOUD (AIVEN - MySQL)
# ==========================================
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

# Driver y Dialecto
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect