# ==========================================
# 1. CONFIGURACION GLOBAL
# ==========================================
spring.application.name=fp-api
server.port=${PORT:5000}
jwt.secret=${JWT_SECRET}

# ==========================================
# 2. CONFIGURACION JPA / HIBERNATE
# ==========================================
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=none

# ==========================================
# 3. CONEXION CLOUD (AIVEN - MySQL)
# ==========================================
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.hikari.maximum-pool-size=3
spring.datasource.hikari.minimum-idle=1
# Driver y Dialecto
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# ==========================================
# 4. SWAGGER / SPRINGDOC
# ==========================================
springdoc.swagger-ui.path=/swagger-ui/index.html
springdoc.swagger-ui.operationsSorter=method

# ==========================================
# 5. MICROSERVICIO IA (Python/FastAPI)
# ==========================================
ia.service.url=${IA_SERVICE_URL}
ia.service.api-key=${IA_SERVICE_API_KEY}